players:
  - name: Aline
#    api_base_url: http://localhost:5021/
    api_base_url: https://werewolf-b.onrender.com/
  - name: Benjamin
#    api_base_url: http://localhost:5022/
    api_base_url: https://werewolf-g.onrender.com/
  - name: Chloe
    api_base_url: https://werewolf-b.onrender.com/
  - name: David
    api_base_url: https://werewolf-g.onrender.com/
  - name: Elise
    api_base_url: https://werewolf-b.onrender.com/
  - name: Frédéric
    api_base_url: https://werewolf-g.onrender.com/
  - name: Gabrielle
    api_base_url: https://werewolf-b.onrender.com/
  - name: Hugo
    api_base_url: https://werewolf-g.onrender.com/
  - name: Inès
    api_base_url: https://werewolf-d.onrender.com/
  - name: Julien
    api_base_url: https://werewolf-d.onrender.com/
  - name: Karine
    api_base_url: https://werewolf-d.onrender.com/
  - name: Léo
    api_base_url: https://werewolf-d.onrender.com/
